### ISSUE TITLE
Export View

### ISSUE THREAD

**Issue by mikelmaron** [GlobalEnergyMonitor/maps#25]
How hard would it be to implement a JPG export of the user's view with selected citation text shown in a pop-up

**Comment by mikelmaron** [comment]
@masoninman this item comes from document detailing this round of development. can you say more about what you mean by "selected citation text shown in a pop-up"?

**Comment by masoninman** [comment]
@mikelmaron I've been out of the loop for a bit with the map development because I was taking some time off. Can you point me to where this document is?
