### ISSUE TITLE
Handle multi-country features in filter

### ISSUE THREAD

**Issue by mikelmaron** [GlobalEnergyMonitor/maps#48]
ex: pipelines

**Comment by TaylorHigginsGEM** [comment]
Also relevant to hydropower plants and GOGET.

Examples: 

[BATOKA GORGE HYDROELECTRIC PLANT](https://globalenergymonitor.org/projects/global-hydropower-tracker/tracker-map/) 

[GREATER TORTUE AHMEYIM GAS COMPLEX (SENEGAL-MAURITANIA)](https://globalenergymonitor.org/projects/global-oil-gas-extraction-tracker/tracker-map/)

**Comment by mikelmaron** [comment]
Must support situation when countries are substrings of each other (Niger / Nigeria)
